import { StyleSheet } from "react-native";

export const theme = {
	colors: {
		background: "#121212",
		card: "#1e1e1e",
		primary: "#3498db",
		success: "#2ecc71",
		warning: "#f1c40f",
		error: "#e74c3c",
		text: "#ffffff",
		subtext: "#666",
		border: "#2d2d2d",
	},
};

export const globalStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: theme.colors.background,
	},
	leftFooter: {
		position: "absolute",
		left: -110,
		top: "50%",
		zIndex: 10,
		transform: [{ rotate: "-90deg" }],
		width: 260,
		backgroundColor: "transparent",
		alignItems: "center",
		justifyContent: "center",
	},
	footerText: {
		color: "#333",
		fontSize: 8,
		fontWeight: "bold",
		letterSpacing: 2,
		textAlign: "center",
	},
	contentBody: {
		flex: 1,
		paddingHorizontal: 24,
	},
	header: {
		alignItems: "center",
		marginBottom: 20,
	},
	logoContainer: {
		width: 52,
		height: 52,
		borderRadius: 14,
		backgroundColor: theme.colors.card,
		justifyContent: "center",
		alignItems: "center",
		marginBottom: 8,
		borderWidth: 1,
		borderColor: theme.colors.border,
	},
	title: {
		fontSize: 20,
		fontWeight: "bold",
		color: theme.colors.text,
		marginBottom: 8,
	},
	statusBox: {
		flexDirection: "row",
		alignItems: "center",
		backgroundColor: theme.colors.card,
		paddingVertical: 6,
		paddingHorizontal: 14,
		borderRadius: 20,
		borderWidth: 1,
		borderColor: theme.colors.border,
	},
	statusDot: {
		width: 8,
		height: 8,
		borderRadius: 4,
		marginRight: 8,
	},
	dotGreen: { backgroundColor: theme.colors.success },
	dotRed: { backgroundColor: theme.colors.error },
	statusText: {
		fontSize: 11,
		color: "#eee",
		fontWeight: "600",
		textTransform: "uppercase",
		letterSpacing: 0.5,
	},
	btnManual: {
		backgroundColor: theme.colors.primary,
		paddingVertical: 24,
		borderRadius: 12,
		alignItems: "center",
		marginBottom: 24,
		shadowColor: "#000",
		shadowOffset: { width: 0, height: 6 },
		shadowOpacity: 0.4,
		shadowRadius: 6,
		elevation: 8,
	},
	btnManualText: {
		color: theme.colors.text,
		fontSize: 15,
		fontWeight: "900",
		letterSpacing: 1,
	},
	historyTitle: {
		fontSize: 11,
		color: "#555",
		fontWeight: "bold",
		textTransform: "uppercase",
		marginBottom: 10,
		letterSpacing: 0.5,
	},
	clipCard: {
		flexDirection: "row",
		backgroundColor: theme.colors.card,
		padding: 14,
		borderRadius: 8,
		alignItems: "center",
		marginBottom: 8,
		borderWidth: 1,
		borderColor: theme.colors.border,
	},
	clipInfo: {
		flex: 1,
		paddingRight: 10,
	},
	metaRow: {
		flexDirection: "row",
		alignItems: "center",
		marginBottom: 4,
	},
	clipTime: {
		fontSize: 10,
		color: theme.colors.subtext,
		fontWeight: "600",
	},
	clipText: {
		fontSize: 13,
		color: "#e0e0e0",
	},
	pendingBadge: {
		backgroundColor: "rgba(241, 196, 15, 0.1)",
		paddingHorizontal: 4,
		paddingVertical: 1,
		borderRadius: 4,
		marginLeft: 6,
		borderWidth: 0.5,
		borderColor: "rgba(241, 196, 15, 0.3)",
	},
	pendingText: {
		fontSize: 8,
		color: theme.colors.warning,
		fontWeight: "bold",
	},
	placeholder: {
		color: "#444",
		fontStyle: "italic",
		textAlign: "center",
		marginTop: 40,
		fontSize: 13,
	},
	toast: {
		position: "absolute",
		top: 50,
		left: "10%",
		right: "10%",
		flexDirection: "row",
		alignItems: "center",
		justifyContent: "center",
		paddingVertical: 10,
		paddingHorizontal: 16,
		borderRadius: 24,
		zIndex: 999,
		borderWidth: 0.5,
	},
	toastSuccess: {
		backgroundColor: "#14231a",
		borderColor: "rgba(46, 204, 113, 0.2)",
	},
	toastWarning: {
		backgroundColor: "#242114",
		borderColor: "rgba(241, 196, 15, 0.2)",
	},
	toastText: {
		color: theme.colors.text,
		fontSize: 12,
		fontWeight: "600",
		marginLeft: 8,
	},
});
